import type { Metadata, Viewport } from "next";
import { SerwistProvider } from "@serwist/next/react";
import "@fontsource-variable/inter";
import "./globals.css";

const APP_NAME = "OASYS";
const APP_DEFAULT_TITLE = "OASYS | Hostel Management";
const APP_TITLE_TEMPLATE = "%s | OASYS";
const APP_DESCRIPTION =
  "Smart Hostel Management Platform for OASYS Institute of Technology.";

export const metadata: Metadata = {
  applicationName: APP_NAME,
  title: {
    default: APP_DEFAULT_TITLE,
    template: APP_TITLE_TEMPLATE,
  },
  description: APP_DESCRIPTION,
  // /manifest.webmanifest is generated by app/manifest.ts and linked
  // into <head> automatically by Next.js, but setting it explicitly
  // here is harmless and keeps the intent obvious.
  manifest: "/manifest.webmanifest",
  icons: {
    // All icon files live under /public/assets (and /public/assets/logo),
    // matching every other static asset reference in this codebase.
    icon: [
      { url: "/assets/favicon.ico", sizes: "any", type: "image/x-icon" },
      { url: "/assets/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/assets/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/assets/logo/icon-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/assets/logo/icon-512x512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/assets/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: APP_DEFAULT_TITLE,
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport: Viewport = {
  // Matches the app's primary purple brand color — colors the browser
  // UI (Android status bar / task switcher) and the PWA splash screen.
  // width/initialScale left at Next.js defaults (device-width / 1),
  // and viewport-fit intentionally left unset so no safe-area/notch
  // behavior changes on existing layouts.
  themeColor: "#6D28D9",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <SerwistProvider
          swUrl="/sw.js"
          disable={process.env.NODE_ENV === "development"}
        >
          {children}
        </SerwistProvider>
      </body>
    </html>
  );
}